spring.application.name=fawry-task
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/grocery
spring.datasource.username=root
spring.datasource.password=******
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false


app.jwt.secret=******************************************
app.jwt.expiration-ms=86400000


mealdb.api.base-url=https://www.themealdb.com/api/json/v1/1

